[package]
edition = "2021"
name = "rust-cargo-chef-test"
version = "0.1.0"
authors = ["Jose Celano <josecelano@gmail.com>"]
description = "A test for cargo chef."
repository = "https://github.com/josecelano/rust-cargo-chef-test"

[profile.dev]
debug = 1
opt-level = 1
lto = "thin"

[profile.release]
debug = 1
opt-level = 3
lto = "fat"
strip = true

[dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "net",
    "sync",
    "macros",
    "signal",
] }

serde = { version = "1.0", features = ["derive"] }
serde_bencode = "^0.2.3"
serde_json = "1.0"
serde_with = "2.0"
hex = "0.4.3"
percent-encoding = "2"
binascii = "0.1"
lazy_static = "1.4"

openssl = { version = "0.10", features = ["vendored"] }

warp = { version = "0.3", features = ["tls"] }

config = "0.13"
toml = "0.5"

log = { version = "0.4", features = ["release_max_level_info"] }
fern = "0.6"
chrono = "0.4"

r2d2 = "0.8"
r2d2_mysql = "21"
r2d2_sqlite = { version = "0.21", features = ["bundled"] }

rand = "0.8"
derive_more = "0.99"
thiserror = "1.0"
futures = "0.3"
async-trait = "0.1"

aquatic_udp_protocol = "0.2"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
mockall = "0.11"
reqwest = { version = "0.11.13", features = ["json"] }
